/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import comments from "strapi-plugin-comments/strapi-admin";
import webtools from "strapi-plugin-webtools/strapi-admin";
import webtoolsAddonSitemap from "webtools-addon-sitemap/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "users-permissions": usersPermissions,
    comments: comments,
    webtools: webtools,
    "webtools-addon-sitemap": webtoolsAddonSitemap,
  },
});
